#!/usr/bin/env bash
# autonomous-agent-spec-loop-pi.sh
#
# Spec-feedback loop agent (pi-native). Unlike the other agents this one is
# TIME-driven, not Linear-state-driven: on a schedule it re-audits the repo's
# implementation against its spec corpus and files divergences as Linear
# Backlog tickets (the human arbitration buffer — autoframe's research agent
# polls Todo, so nothing executes until a human promotes a ticket).
#
# Pipeline per run (all logic lives IN THE TARGET REPO, this script just drives it):
#   1. pin: git fetch + hard-reset to origin/$GIT_BASE_BRANCH
#   2. run: bash scripts/spec-loop.sh   (describer → comparator → filer chain)
#   3. persist: commit + push docs/reviews/** so gap-id continuity and the
#      audit trail survive this ephemeral container
#
# Env:
#   SPEC_LOOP_RUN_ON_START   run immediately on container start (default: 1)
#   SPEC_LOOP_INTERVAL_S     seconds between runs (default: 86400 = nightly)
#   SPEC_LOOP_AREAS          space-separated area filter (default: all active)
#   SPEC_LOOP_PUSH_REPORTS   commit+push docs/reviews after run (default: 1)
#   GIT_BASE_BRANCH          branch to audit (default: develop)
#
# Usage:
#   ./scripts/autonomous-agent-spec-loop-pi.sh [--once]

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$SCRIPT_DIR/autonomous-spec-loop-pi-logs"
mkdir -p "$LOG_DIR"

REPO_DIR="${WORKSPACE:-/workspace}/repo"
BASE_BRANCH="${GIT_BASE_BRANCH:-develop}"
RUN_ON_START="${SPEC_LOOP_RUN_ON_START:-1}"
INTERVAL_S="${SPEC_LOOP_INTERVAL_S:-86400}"
PUSH_REPORTS="${SPEC_LOOP_PUSH_REPORTS:-1}"
ONCE=0
[[ "${1:-}" == "--once" ]] && ONCE=1

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$1] ${*:2}" | tee -a "$LOG_DIR/agent.log"
}

if [[ -z "${LINEAR_API_KEY:-}" ]]; then
    log ERROR "LINEAR_API_KEY not set — cannot file gap tickets"
    exit 2
fi

run_spec_loop() {
    local stamp run_log
    stamp="$(date +%Y%m%d-%H%M%S)"
    run_log="$LOG_DIR/spec-loop-${stamp}.log"

    cd "$REPO_DIR" || { log ERROR "repo not found at $REPO_DIR"; return 1; }

    # ── 1. Pin to the tip of the base branch ─────────────────────────────────
    log INFO "Pinning to origin/$BASE_BRANCH"
    git fetch origin "$BASE_BRANCH" >>"$run_log" 2>&1 || { log ERROR "git fetch failed"; return 1; }
    git checkout -B "$BASE_BRANCH" "origin/$BASE_BRANCH" >>"$run_log" 2>&1 || { log ERROR "git checkout failed"; return 1; }
    local sha; sha="$(git rev-parse --short HEAD)"

    if [[ ! -x scripts/spec-loop.sh ]]; then
        log WARN "scripts/spec-loop.sh not present on $BASE_BRANCH@$sha — has the spec-loop branch been merged?"
        return 1
    fi

    # ── 2. Run the in-repo loop (describer → comparator → filer) ─────────────
    log INFO "Running spec-loop @ $sha (areas: ${SPEC_LOOP_AREAS:-all})"
    # shellcheck disable=SC2086
    bash scripts/spec-loop.sh ${SPEC_LOOP_AREAS:-} >>"$run_log" 2>&1
    local rc=$?
    if [[ $rc -ne 0 ]]; then
        log ERROR "spec-loop.sh exited rc=$rc — see $run_log"
        return $rc
    fi

    # ── 3. Persist gap reports + observed notes back to the remote ───────────
    # Gap-id continuity (comparator numbers from existing reports) and the
    # audit trail must survive this ephemeral clone. Docs-only push.
    if [[ "$PUSH_REPORTS" == "1" ]]; then
        git add docs/reviews/ >>"$run_log" 2>&1
        if ! git diff --cached --quiet; then
            git -c user.name="spec-loop-agent" -c user.email="spec-loop@autoframe.local" \
                commit -m "GYL-440: spec-loop nightly audit @ ${sha} ($(date +%Y-%m-%d))

Automated gap report + observed-behaviour refresh. Docs-only.
Generated by autoframe spec-loop agent." >>"$run_log" 2>&1
            if git push origin "$BASE_BRANCH" >>"$run_log" 2>&1; then
                log INFO "Pushed docs/reviews updates to $BASE_BRANCH"
            else
                log WARN "Push failed (branch moved?) — reports remain in tickets; see $run_log"
                git reset --hard "origin/$BASE_BRANCH" >>"$run_log" 2>&1
            fi
        else
            log INFO "No report changes to push"
        fi
    fi

    log INFO "Run complete — log: $run_log"
}

# ── Main loop ─────────────────────────────────────────────────────────────────

log INFO "spec-loop agent started (interval=${INTERVAL_S}s, base=$BASE_BRANCH, once=$ONCE)"

if [[ "$RUN_ON_START" == "1" || "$ONCE" == "1" ]]; then
    run_spec_loop || log WARN "initial run failed"
    [[ "$ONCE" == "1" ]] && exit 0
fi

while true; do
    log INFO "Sleeping ${INTERVAL_S}s until next audit"
    sleep "$INTERVAL_S"
    run_spec_loop || log WARN "scheduled run failed"
done
